### ISSUE TITLE
Community detection not working

### ISSUE THREAD

**Issue by vinicvaz** [EthoML/VAME#16]
I tried to run the demo.py pipeline with `vame.community(config, show_umap=False, cut_tree=2)` post processing and I got the following error:
```bash
line 448, in get_cohort_community_labels
    clust = np.asarray(communities_all[i])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

Looks like the `communities_all` array is not homogeneous for this case... Looking to this variable I have the following inhomogeneous array: `[[[3, 10, 7, 5, 13], [6, 1, 8, 2], [9, 4, 14], [12, 11, 0]]]`

Steps to reproduce the above behavior:

1. Run the `demo.py` from `tests` branch uncommenting the `vame.community(config, show_umap=False, cut_tree=2)`  line.
2. Set the `config.yaml` project file to use `max_epochs=20`

What may be causing this issue? Can it be related to the amount of epochs I'm using to test?

**Comment by bendichter** [comment]
Can we get away with keeping it as a list of lists?
