### ISSUE TITLE
Relocate IQR cleaning into egocentric_alignment() and rename function

### ISSUE THREAD

**Issue by katiekly** [EthoML/VAME#22]
Currently, `create_trainset()` uses IQR cleaning to nan and interpolate over outlier points to make the pose trajectories smoother. This data cleaning step should be relocated into `egocentric_alignment()` and then rename `egocentric_alignment()` to, for example, `preprocess_and_egocentric_alignment()`.

**Comment by luiztauffer** [comment]
it might make sense to create an explicit `vame.preprocessing()` step, where we can include options for:
- egocentric alignment
- normalization, IQR, filters, ...
- other preprocessing operations, such as the ones offered by `movement`

**Comment by luiztauffer** [comment]
covered by https://github.com/EthoML/VAME/issues/119
