### ISSUE TITLE
Community analysis breaking for cohort=True and show_umap=True

### ISSUE THREAD

**Issue by vinicvaz** [EthoML/VAME#32]
When running `vame.community(cohort=True, show_umap=True)` the function breaks.

The problem is happening in this line: https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/community_analysis.py#L478

The problem is that in [line 577](https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/community_analysis.py#L577C12-L578C62) we pass a list of files to the
[umap_embedding](https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/community_analysis.py#L460) function, but it expects a single file and not an array of files paths.
How should we handle that? Should we create an umap embedding for each file when cohort=True and then agg them?

**Comment by vinicvaz** [comment]
```
--> [479](https://file+.vscode-resource.vscode-cdn.net/home/vinicius/Documents/work/catalyst/VAME/examples/~/Documents/work/catalyst/VAME/src/vame/analysis/community_analysis.py:479) folder = os.path.join(cfg['project_path'],"results",file,model_name, parametrization +'-'+str(n_cluster),"")
    [480](https://file+.vscode-resource.vscode-cdn.net/home/vinicius/Documents/work/catalyst/VAME/examples/~/Documents/work/catalyst/VAME/src/vame/analysis/community_analysis.py:480) latent_vector = np.load(os.path.join(folder,'latent_vector_'+file+'.npy'))
    [482](https://file+.vscode-resource.vscode-cdn.net/home/vinicius/Documents/work/catalyst/VAME/examples/~/Documents/work/catalyst/VAME/src/vame/analysis/community_analysis.py:482) num_points = cfg['num_points']

File <frozen posixpath>:90, in join(a, *p)

File <frozen genericpath>:152, in _check_arg_types(funcname, *args)

TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'
```

**Comment by vinicvaz** [comment]
It is also breaking with `cohort=False` and `show_umap=True`. But in this case the problem is other.

Error track:
```
-> [481] plt.scatter(embed[:,0], embed[:,1],  c=community_labels_all[0, :num_points], cmap='Spectral', s=2, alpha=1)
    [482] plt.colorbar(boundaries=np.arange(np.max(num)+2)-0.5).set_ticks(np.arange(np.max(num)+1))
    [483] plt.gca().set_aspect('equal', 'datalim')

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

The `community_labels_all` array is of shape (X,) so the slice is wrong. I think we can fix it by removing the first index of the slice
```
plt.scatter(embed[:,0], embed[:,1],  c=community_labels_all[:num_points], cmap='Spectral', s=2, alpha=1)
```
I added this fix to the PR #33

**Comment by katiekly** [comment]
Hi, we encountered a bug on line 499 in community_anlaysis.py when `create_community_bag()` is called, but I'm confused why the code entered the if statement at line 496 when cohort == True is explicitly defined.

**Comment by luiztauffer** [comment]
@katiekly the code shouldn't enter there if `cohort=true`.
This part of the code seems to be WIP

https://github.com/EthoML/VAME/blob/5247b82946f15e2cb5224e99cef7980506962875/src/vame/analysis/community_analysis.py#L496-L500

this statement `elif not cohort:` is also unnecessary, I'll change it to a simple `else`

**Comment by luiztauffer** [comment]
since we separated the umap visualization function from community analysis, this Issue is outdated. Therefore I'm closing it.
It can still happen, though, and I described the source of it here: https://github.com/EthoML/VAME/issues/84
