### ISSUE TITLE
create_video function breaking with label = None

### ISSUE THREAD

**Issue by vinicvaz** [EthoML/VAME#41]
When running the function [gif](https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/gif_creator.py#L81) with `label = None` the function [create_video](https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/gif_creator.py#L25) is breaking because this function expect the label to be a numpy ndarray [here](https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/gif_creator.py#L71) and for this case it is None. 
How should we handle this?
Can we replace this line
https://github.com/EthoML/VAME/blob/59d5d730d9c8f9ca048022bd3224ddfc58891863/src/vame/analysis/gif_creator.py#L71

with:
```
if clabel:
   ax1.scatter(embed[:num_points,0], embed[:num_points,1], c=clabel[:num_points], cmap='Spectral', s=1, alpha=0.4)
else:
   ax1.scatter(embed[:num_points,0], embed[:num_points,1], s=1, alpha=0.4)
```

With this, the cmap will be ignored for `label=None`

**Comment by vinicvaz** [comment]
@DrSRMiller @katiekly would love to hear your thoughts on that

**Comment by katiekly** [comment]
yes, please try replacing and can you let us know if the output is similar to the gif shown in [here](https://github.com/LINCellularNeuroscience/VAME)?
