### ISSUE TITLE
Community function not outputing 'Cohort Community Bag' and 'Hierarchy' list

### ISSUE THREAD

**Issue by katiekly** [EthoML/VAME#88]
I'm using vame 0.5.0 from the main branch. vame.community() is not working as expected, where Cohort Community Bag and the Hierarchy list isn't outputted. 

Some changes to improve this function:
-Increase the figure size to be twice as wide to improve visibility.
-Comment out Lines 497-511 in community_analysis.py. For now, let's only support creating the cohort-level dendrogram.
 (These last two bullets are to reproduce the original dendrogram outputs)
-Remove all blue circles and text that isn't a leaf.
-Leaf node size should be proportional to motif usage.

The expected dendrogram figure should look like this. This was created from the [original VAME](https://github.com/LINCellularNeuroscience/VAME/blob/master/vame/analysis/community_analysis.py). 
[Cohort_Balanced_Dendrogram.pdf](https://github.com/user-attachments/files/17214477/Cohort_Balanced_Dendrogram.pdf)

Here are some sample outputs of the current function :

![image](https://github.com/user-attachments/assets/b5349730-03f0-4ba5-87c1-238885c875cb)
![image](https://github.com/user-attachments/assets/f7bdd67b-6b91-46ff-9ca4-53798d3cffed)
![image](https://github.com/user-attachments/assets/dbae7e7d-2fdb-4553-ad3d-cdcf44e82649)
![image](https://github.com/user-attachments/assets/2ba718fd-c440-48ef-add2-1299ca13df08)

**Comment by luiztauffer** [comment]
@katiekly how about this?

![image](https://github.com/user-attachments/assets/31890e55-6e80-4b73-9c4b-fc92c1f65e96)
