### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by xiaoxionglab** [EthoML/VAME#93]
I installed the latest version, but got the following error when running "import vame":

----> [4](vscode-notebook-cell:?execution_count=1&line=4) import vame

File d:\ProgramData\anaconda3\envs\vame\Lib\site-packages\vame\__init__.py:18
     [16](file:///D:/ProgramData/anaconda3/envs/vame/Lib/site-packages/vame/__init__.py:16) from vame.model import train_model
     [17](file:///D:/ProgramData/anaconda3/envs/vame/Lib/site-packages/vame/__init__.py:17) from vame.model import evaluate_model
---> [18](file:///D:/ProgramData/anaconda3/envs/vame/Lib/site-packages/vame/__init__.py:18) from vame.analysis import pose_segmentation

**Comment by luiztauffer** [comment]
hi @xiaoxionglab , thanks for reporting this. Could you please paste the full error track to help me debug?

**Comment by xiaoxionglab** [comment]
I found the issue—it was related to the permission for importing from the vame environment. Once I ran VSCode as an administrator, everything worked smoothly. Thanks!
